GET http://localhost:3000

###
POST http://localhost:3000/user/register
###
POST http://localhost:3000/user/refresh-token
###
POST http://localhost:3000/user/login
###
POST http://localhost:3000/user/logout